// <auto-generated />
namespace Cooxi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addinstauseridname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinstauseridname));
        
        string IMigrationMetadata.Id
        {
            get { return "201603021116183_add-insta-userid-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
